from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
VLLM_REPO_PATH = PROJECT_ROOT / "vllm-0.10.1"
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = DATA_DIR / "output"
DATASETS_DIR = PROJECT_ROOT / "datasets"

MAX_CHUNK_SIZE = 2000
DOC_CHUNK_OVERLAP = 200

DEFAULT_K = 10

MAX_INDEXING_TIME = 300
MAX_RETRIEVAL_TIME = 60
MAX_ANSWER_TIME = 1.8

DEFAULT_MODEL = "ollama_chat/qwen3:0.6b"
MAX_CONTEXT_CHARS = 8000
LLM_TIMEOUT = 30

OVERLAP_THRESHOLD = 0.05

USE_CACHE = True
BATCH_SIZE = 100
